### ISSUE TITLE
Pandas KeyError during kickoff analysis

### ISSUE THREAD

**Issue by nikkelma** [SaltieRL/carball#168]
Attempted to analyze this replay: [https://cdn.discordapp.com/attachments/594899039355666432/599450806428762113/21DF74C045EEF30284D1339ECEC561D4.replay](https://cdn.discordapp.com/attachments/594899039355666432/599450806428762113/21DF74C045EEF30284D1339ECEC561D4.replay) but carball crashed.

Happy to provide any other info you'd need!

Python stack trace:
```
Traceback (most recent call last):
  File "stats_init.py", line 10, in <module>
    carball.analyze_replay_file(init_replay_file_path)
  File "<project-folder>\venv\lib\site-packages\carball\decompile_replays.py", line 52, in analyze_replay_file
    analysis.create_analysis()
  File "<project-folder>\venv\lib\site-packages\carball\analysis\analysis_manager.py", line 59, in create_analysis
    data_frame, kickoff_frames, first_touch_frames)
  File "<project-folder>\venv\lib\site-packages\carball\analysis\analysis_manager.py", line 83, in perform_full_analysis
    self.events_creator.create_events(game, proto_game, player_map, data_frame, kickoff_frames, first_touch_frames)
  File "<project-folder>\venv\lib\site-packages\carball\analysis\events\event_creator.py", line 32, in create_events
    self.calculate_kickoff_stats(game, proto_game, player_map, data_frame, kickoff_frames, first_touch_frames)
  File "<project-folder>\venv\lib\site-packages\carball\analysis\events\event_creator.py", line 38, in calculate_kickoff_stats
    kickoffs = BaseKickoff.get_kickoffs_from_game(game, proto_game, self.id_creator, player_map, data_frame, kickoff_frames, first_touch_frames)
  File "<project-folder>\venv\lib\site-packages\carball\analysis\events\kickoff_detection\kickoff_analysis.py", line 40, in get_kickoffs_from_game
    BaseKickoff.set_jumps(kPlayer, player, data_frame, frame, end_frame)
  File "<project-folder>\venv\lib\site-packages\carball\analysis\events\kickoff_detection\kickoff_analysis.py", line 56, in set_jumps
    if collected_boost_df[f] == True:
  File "<project-folder>\venv\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "<project-folder>\venv\lib\site-packages\pandas\core\indexes\base.py", line 4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 9434
```

**Comment by Longi94** [comment]
This was probably fixed with https://github.com/SaltieRL/carball/pull/163 already, I'll check later

**Comment by nikkelma** [comment]
Thank you @Longi94 for the quick response and fix! I'll make the needed change to my virtual environment's copy of carball for the time being, can't wait for the pypi release 🎉
