### ISSUE TITLE
Invalid index getting kickoff frames

### ISSUE THREAD

**Issue by dtracers** [SaltieRL/carball#194]
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 53, in analyze_replay_file
    analysis.create_analysis()
  File "/env/local/lib/python3.7/site-packages/carball/analysis/analysis_manager.py", line 56, in create_analysis
    kickoff_frames, first_touch_frames = self.get_kickoff_frames(self.game, self.protobuf_game, data_frame)
  File "/env/local/lib/python3.7/site-packages/carball/analysis/analysis_manager.py", line 138, in get_kickoff_frames
    ] = goal_number
IndexError: index 0 is out of bounds for axis 0 with size 0
```

https://cdn.discordapp.com/attachments/493849514680254468/633506591794003989/index_error_kickof_frames.replay

**Comment by dtracers** [comment]
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 53, in analyze_replay_file
    analysis.create_analysis()
  File "/env/local/lib/python3.7/site-packages/carball/analysis/analysis_manager.py", line 56, in create_analysis
    kickoff_frames, first_touch_frames = self.get_kickoff_frames(self.game, self.protobuf_game, data_frame)
  File "/env/local/lib/python3.7/site-packages/carball/analysis/analysis_manager.py", line 138, in get_kickoff_frames
    ] = goal_number
IndexError: index 2 is out of bounds for axis 0 with size 2
```

Alternative version?
Check both

https://cdn.discordapp.com/attachments/493849514680254468/633508929221165076/index_error_during_get_kickoff_frames.replay
