### ISSUE TITLE
game.initialize(loaded_json=_json)  |  Keyerror: 'content'

### ISSUE THREAD

**Issue by Eksnoverse** [SaltieRL/carball#220]
Traceback (most recent call last):
  File "H:/Program Files/RLBotGUI/MyBots/NeurBot/src/TrainingData/main.py", line 12, in <module>
    createTrainingData.create_data_from_replay(_replay_path, _output_path, _json_path, save_json=True)
  File "H:\Program Files\RLBotGUI\MyBots\NeurBot\src\TrainingData\createTrainingData.py", line 155, in create_data_from_replay
    createAndSaveReplayTrainingDataFromJSON(json_path, outputFileName=output_path)
  File "H:\Program Files\RLBotGUI\MyBots\NeurBot\src\TrainingData\createTrainingData.py", line 128, in createAndSaveReplayTrainingDataFromJSON
    replayData = convert_json_to_game_frames(replayPath)
  File "H:\Program Files\RLBotGUI\MyBots\NeurBot\src\TrainingData\createTrainingData.py", line 60, in convert_json_to_game_frames
    game.initialize(loaded_json=_json)
  File "H:\Program Files\RLBotGUI\MyBots\NeurBot\src\TrainingData\venv\lib\site-packages\carball\json_parser\game.py", line 61, in initialize
    self.replay_data = self.replay['content']['body']['frames']
KeyError: 'content'

I have tried many many replays both from me and a lot of other people but it won't work.

**Comment by Sciguymjm** [comment]
You're trying to initialize the JSON parser `game` object with the JSON representation of the resultant stats i.e. the proto.
