### ISSUE TITLE
Encoding issue with names

### ISSUE THREAD

**Issue by Sciguymjm** [SaltieRL/carball#24]
Carball throws an error about `latin-1` encoding issues in replays with Unicode names.

**Comment by f90** [comment]
Having the same issue, looks like this:

```
Replay name not found
Dropping these columns[('game', 'is_overtime')]
Goal is not shot: frame_number: 5121
player_id {
  id: "3318206596339624645"
}
collision_distance: 105.97723388671875
ball_data {
  pos_x: -1015.8499755859375
  pos_y: 3573.989990234375
  pos_z: 102.56999969482422
}
pass_: true
passed: true
goal: true
assisted: true
distance: 3701.322509765625
distance_to_goal: 1570.5894775390625
previous_hit_frame_number: 5059
goal_number: 2
is_kickoff: false

Goal is not shot: frame_number: 5665
player_id {
  id: "3318206596339624645"
}
collision_distance: 145.95846557617188
ball_data {
  pos_x: -1884.3199462890625
  pos_y: -3587.179931640625
  pos_z: 243.30999755859375
}
goal: true
distance: 4005.416259765625
distance_to_goal: 8782.9638671875
previous_hit_frame_number: 5611
goal_number: 3
is_kickoff: false

Goal is not shot: frame_number: 9009
player_id {
  id: "3318206596339624645"
}
collision_distance: 236.06211853027344
ball_data {
  pos_x: 3557.739990234375
  pos_y: 694.3900146484375
  pos_z: 1355.8399658203125
}
pass_: true
passed: true
goal: true
assisted: true
aerial: true
distance: 3844.341796875
distance_to_goal: 6292.79345703125
previous_hit_frame_number: 8867
goal_number: 5
is_kickoff: false

Failure to write pandas [] to memory: 'latin-1' codec can't encode character '\u2122' in position 1839: ordinal not in range(256)
Traceback (most recent call last):
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/carball/analysis/utils/pandas_manager.py", line 20, in safe_write_pandas_to_memory
    return PandasManager.write_numpy_to_memory(df)
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/carball/analysis/utils/pandas_manager.py", line 35, in write_numpy_to_memory
    write_array_to_file(compressed_array, numpy_array)
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/carball/analysis/utils/numpy_manager.py", line 17, in write_array_to_file
    bytes = convert_numpy_array(array)
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/carball/analysis/utils/numpy_manager.py", line 30, in convert_numpy_array
    np.save(compressed_array, numpy_array, allow_pickle=True, fix_imports=False)
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/numpy/lib/npyio.py", line 536, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/numpy/lib/format.py", line 608, in write_array
    version)
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/numpy/lib/format.py", line 351, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/home/daniel/envs/replaymodels/lib/python3.6/site-packages/numpy/compat/py3k.py", line 36, in asbytes
    return str(s).encode('latin1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2122' in position 1839: ordinal not in range(256)
```
