### ISSUE TITLE
Fail to install: ModuleNotFoundError: No module named 'init'

### ISSUE THREAD

**Issue by Gurey** [SaltieRL/carball#245]
Hi!

I'm having some trouble installing carball with pip.

I'm not that familiar with Python and pip so this might be a problem on my end, but hopefully you can help me to rule it out.

`pip.exe install carball`
yields this output 
(sorry for the TLDR-like cmd print but i don't want to leave anything out.)

```
pip.exe install carball
Collecting carball
  Using cached carball-0.6.36.tar.gz (5.1 MB)
Requirement already satisfied: pandas==0.24.2 in c:\python\lib\site-packages (from carball) (0.24.2)
Requirement already satisfied: protobuf==3.6.1 in c:\python\lib\site-packages (from carball) (3.6.1)
Requirement already satisfied: xlrd==1.1.0 in c:\python\lib\site-packages (from carball) (1.1.0)
Requirement already satisfied: numpy==1.17.0 in c:\python\lib\site-packages (from carball) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\python\lib\site-packages (from pandas==0.24.2->carball) (2.8.1)
Requirement already satisfied: pytz>=2011k in c:\python\lib\site-packages (from pandas==0.24.2->carball) (2020.1)
Requirement already satisfied: setuptools in c:\python\lib\site-packages (from protobuf==3.6.1->carball) (46.4.0)
Requirement already satisfied: six>=1.9 in c:\python\lib\site-packages (from protobuf==3.6.1->carball) (1.15.0)
Building wheels for collected packages: carball
  Building wheel for carball (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MyUser\\AppData\\Local\\Temp\\pip-install-ak5nbgls\\carball\\setup.py'"'"'; __file__='"'"'C:\\Users\\MyUser\\AppData\\Local\\Temp\\pip-install-ak5nbgls\\carball\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\MyUser\AppData\Local\Temp\pip-wheel-t4j_0wlm'
       cwd: C:\Users\MyUser\AppData\Local\Temp\pip-install-ak5nbgls\carball\
  Complete output (271 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\carball
  copying carball\command_line.py -> build\lib\carball
  copying carball\decompile_replays.py -> build\lib\carball
  copying carball\__init__.py -> build\lib\carball
  creating build\lib\utils
  copying utils\create_proto.py -> build\lib\utils
  copying utils\import_fixer.py -> build\lib\utils
  copying utils\__init__.py -> build\lib\utils
  creating build\lib\carball\analysis
  copying carball\analysis\analysis_manager.py -> build\lib\carball\analysis
  copying carball\analysis\__init__.py -> build\lib\carball\analysis
  creating build\lib\carball\controls
  copying carball\controls\controls.py -> build\lib\carball\controls
  copying carball\controls\rotations.py -> build\lib\carball\controls
  copying carball\controls\__init__.py -> build\lib\carball\controls
  creating build\lib\carball\extras
  copying carball\extras\per_goal_analysis.py -> build\lib\carball\extras
  copying carball\extras\__init__.py -> build\lib\carball\extras
  creating build\lib\carball\json_parser
  copying carball\json_parser\actor_parsing.py -> build\lib\carball\json_parser
  copying carball\json_parser\bots.py -> build\lib\carball\json_parser
  copying carball\json_parser\dropshot.py -> build\lib\carball\json_parser
  copying carball\json_parser\frame_parser.py -> build\lib\carball\json_parser
  copying carball\json_parser\game.py -> build\lib\carball\json_parser
  copying carball\json_parser\game_info.py -> build\lib\carball\json_parser
  copying carball\json_parser\goal.py -> build\lib\carball\json_parser
  copying carball\json_parser\player.py -> build\lib\carball\json_parser
  copying carball\json_parser\team.py -> build\lib\carball\json_parser
  copying carball\json_parser\__init__.py -> build\lib\carball\json_parser
  creating build\lib\carball\rattletrap
  copying carball\rattletrap\check_rattletrap_version.py -> build\lib\carball\rattletrap
  copying carball\rattletrap\rattletrap_utils.py -> build\lib\carball\rattletrap
  copying carball\rattletrap\run_rattletrap.py -> build\lib\carball\rattletrap
  copying carball\rattletrap\__init__.py -> build\lib\carball\rattletrap
  creating build\lib\carball\tests
  copying carball\tests\analysis_test.py -> build\lib\carball\tests
  copying carball\tests\conftest.py -> build\lib\carball\tests
  copying carball\tests\export_test.py -> build\lib\carball\tests
  copying carball\tests\game_creation_test.py -> build\lib\carball\tests
  copying carball\tests\read_pandas_test.py -> build\lib\carball\tests
  copying carball\tests\setup_tests.py -> build\lib\carball\tests
  copying carball\tests\tiles_test.py -> build\lib\carball\tests
  copying carball\tests\utils.py -> build\lib\carball\tests
  copying carball\tests\__init__.py -> build\lib\carball\tests
  creating build\lib\carball\analysis\cleaner
  copying carball\analysis\cleaner\cleaner.py -> build\lib\carball\analysis\cleaner
  copying carball\analysis\cleaner\frame_cleaner.py -> build\lib\carball\analysis\cleaner
  copying carball\analysis\cleaner\__init__.py -> build\lib\carball\analysis\cleaner
  creating build\lib\carball\analysis\constants
  copying carball\analysis\constants\basic_math.py -> build\lib\carball\analysis\constants
  copying carball\analysis\constants\dropshot.py -> build\lib\carball\analysis\constants
  copying carball\analysis\constants\field_constants.py -> build\lib\carball\analysis\constants
  copying carball\analysis\constants\playlist.py -> build\lib\carball\analysis\constants
  copying carball\analysis\constants\__init__.py -> build\lib\carball\analysis\constants
  creating build\lib\carball\analysis\events
  copying carball\analysis\events\carry_detection.py -> build\lib\carball\analysis\events
  copying carball\analysis\events\event_creator.py -> build\lib\carball\analysis\events
  copying carball\analysis\events\__init__.py -> build\lib\carball\analysis\events
  creating build\lib\carball\analysis\saltie_game
  copying carball\analysis\saltie_game\saltie_game.py -> build\lib\carball\analysis\saltie_game
  copying carball\analysis\saltie_game\__init__.py -> build\lib\carball\analysis\saltie_game
  creating build\lib\carball\analysis\simulator
  copying carball\analysis\simulator\ball_simulator.py -> build\lib\carball\analysis\simulator
  copying carball\analysis\simulator\bounce.py -> build\lib\carball\analysis\simulator
  copying carball\analysis\simulator\map_constants.py -> build\lib\carball\analysis\simulator
  copying carball\analysis\simulator\__init__.py -> build\lib\carball\analysis\simulator
  creating build\lib\carball\analysis\stats
  copying carball\analysis\stats\stats.py -> build\lib\carball\analysis\stats
  copying carball\analysis\stats\stats_list.py -> build\lib\carball\analysis\stats
  copying carball\analysis\stats\stats_manager.py -> build\lib\carball\analysis\stats
  copying carball\analysis\stats\__init__.py -> build\lib\carball\analysis\stats
  creating build\lib\carball\analysis\utils
  copying carball\analysis\utils\json_encoder.py -> build\lib\carball\analysis\utils
  copying carball\analysis\utils\numpy_manager.py -> build\lib\carball\analysis\utils
  copying carball\analysis\utils\pandas_manager.py -> build\lib\carball\analysis\utils
  copying carball\analysis\utils\proto_manager.py -> build\lib\carball\analysis\utils
  copying carball\analysis\utils\split_location.py -> build\lib\carball\analysis\utils
  copying carball\analysis\utils\__init__.py -> build\lib\carball\analysis\utils
  creating build\lib\carball\analysis\events\boost_pad_detection
  copying carball\analysis\events\boost_pad_detection\pickup_analysis.py -> build\lib\carball\analysis\events\boost_pad_detection
  copying carball\analysis\events\boost_pad_detection\__init__.py -> build\lib\carball\analysis\events\boost_pad_detection
  creating build\lib\carball\analysis\events\bump_detection
  copying carball\analysis\events\bump_detection\bump_analysis.py -> build\lib\carball\analysis\events\bump_detection
  copying carball\analysis\events\bump_detection\__init__.py -> build\lib\carball\analysis\events\bump_detection
  creating build\lib\carball\analysis\events\dropshot
  copying carball\analysis\events\dropshot\ball.py -> build\lib\carball\analysis\events\dropshot
  copying carball\analysis\events\dropshot\damage.py -> build\lib\carball\analysis\events\dropshot
  copying carball\analysis\events\dropshot\__init__.py -> build\lib\carball\analysis\events\dropshot
  creating build\lib\carball\analysis\events\fifty_fifty
  copying carball\analysis\events\fifty_fifty\fifty_analysis.py -> build\lib\carball\analysis\events\fifty_fifty
  copying carball\analysis\events\fifty_fifty\__init__.py -> build\lib\carball\analysis\events\fifty_fifty     
  creating build\lib\carball\analysis\events\hit_detection
  copying carball\analysis\events\hit_detection\base_hit.py -> build\lib\carball\analysis\events\hit_detection 
  copying carball\analysis\events\hit_detection\hit_analysis.py -> build\lib\carball\analysis\events\hit_detection
  copying carball\analysis\events\hit_detection\__init__.py -> build\lib\carball\analysis\events\hit_detection 
  creating build\lib\carball\analysis\events\hit_pressure
  copying carball\analysis\events\hit_pressure\pressure_analysis.py -> build\lib\carball\analysis\events\hit_pressure
  copying carball\analysis\events\hit_pressure\__init__.py -> build\lib\carball\analysis\events\hit_pressure   
  creating build\lib\carball\analysis\events\kickoff_detection
  copying carball\analysis\events\kickoff_detection\kickoff_analysis.py -> build\lib\carball\analysis\events\kickoff_detection
  copying carball\analysis\events\kickoff_detection\__init__.py -> build\lib\carball\analysis\events\kickoff_detection
  creating build\lib\carball\analysis\events\hit_detection\hitbox
  copying carball\analysis\events\hit_detection\hitbox\car.py -> build\lib\carball\analysis\events\hit_detection\hitbox
  copying carball\analysis\events\hit_detection\hitbox\hitbox.py -> build\lib\carball\analysis\events\hit_detection\hitbox
  copying carball\analysis\events\hit_detection\hitbox\__init__.py -> build\lib\carball\analysis\events\hit_detection\hitbox
  creating build\lib\carball\analysis\saltie_game\metadata
  copying carball\analysis\saltie_game\metadata\ApiDemo.py -> build\lib\carball\analysis\saltie_game\metadata  
  copying carball\analysis\saltie_game\metadata\ApiGame.py -> build\lib\carball\analysis\saltie_game\metadata  
  copying carball\analysis\saltie_game\metadata\ApiGoal.py -> build\lib\carball\analysis\saltie_game\metadata  
  copying carball\analysis\saltie_game\metadata\ApiMutators.py -> build\lib\carball\analysis\saltie_game\metadata
  copying carball\analysis\saltie_game\metadata\ApiPlayer.py -> build\lib\carball\analysis\saltie_game\metadata
  copying carball\analysis\saltie_game\metadata\ApiPlayerCameraSettings.py -> build\lib\carball\analysis\saltie_game\metadata
  copying carball\analysis\saltie_game\metadata\ApiPlayerLoadout.py -> build\lib\carball\analysis\saltie_game\metadata
  copying carball\analysis\saltie_game\metadata\ApiTeam.py -> build\lib\carball\analysis\saltie_game\metadata  
  copying carball\analysis\saltie_game\metadata\__init__.py -> build\lib\carball\analysis\saltie_game\metadata 
  creating build\lib\carball\analysis\stats\ball_forward
  copying carball\analysis\stats\ball_forward\distance_hit_ball_forward.py -> build\lib\carball\analysis\stats\ball_forward
  copying carball\analysis\stats\ball_forward\__init__.py -> build\lib\carball\analysis\stats\ball_forward     
  creating build\lib\carball\analysis\stats\boost
  copying carball\analysis\stats\boost\boost.py -> build\lib\carball\analysis\stats\boost
  copying carball\analysis\stats\boost\__init__.py -> build\lib\carball\analysis\stats\boost
  creating build\lib\carball\analysis\stats\controls
  copying carball\analysis\stats\controls\controls.py -> build\lib\carball\analysis\stats\controls
  copying carball\analysis\stats\controls\__init__.py -> build\lib\carball\analysis\stats\controls
  creating build\lib\carball\analysis\stats\dribbles
  copying carball\analysis\stats\dribbles\ball_carry.py -> build\lib\carball\analysis\stats\dribbles
  copying carball\analysis\stats\dribbles\__init__.py -> build\lib\carball\analysis\stats\dribbles
  creating build\lib\carball\analysis\stats\dropshot
  copying carball\analysis\stats\dropshot\ball_phase_times.py -> build\lib\carball\analysis\stats\dropshot     
  copying carball\analysis\stats\dropshot\damage.py -> build\lib\carball\analysis\stats\dropshot
  copying carball\analysis\stats\dropshot\goals.py -> build\lib\carball\analysis\stats\dropshot
  copying carball\analysis\stats\dropshot\__init__.py -> build\lib\carball\analysis\stats\dropshot
  creating build\lib\carball\analysis\stats\kickoffs
  copying carball\analysis\stats\kickoffs\kickoff_stat.py -> build\lib\carball\analysis\stats\kickoffs
  copying carball\analysis\stats\kickoffs\__init__.py -> build\lib\carball\analysis\stats\kickoffs
  creating build\lib\carball\analysis\stats\possession
  copying carball\analysis\stats\possession\ball_distances.py -> build\lib\carball\analysis\stats\possession   
  copying carball\analysis\stats\possession\per_possession.py -> build\lib\carball\analysis\stats\possession   
  copying carball\analysis\stats\possession\possession.py -> build\lib\carball\analysis\stats\possession       
  copying carball\analysis\stats\possession\turnovers.py -> build\lib\carball\analysis\stats\possession        
  copying carball\analysis\stats\possession\__init__.py -> build\lib\carball\analysis\stats\possession
  creating build\lib\carball\analysis\stats\rumble
  copying carball\analysis\stats\rumble\goals.py -> build\lib\carball\analysis\stats\rumble
  copying carball\analysis\stats\rumble\rumble.py -> build\lib\carball\analysis\stats\rumble
  copying carball\analysis\stats\rumble\__init__.py -> build\lib\carball\analysis\stats\rumble
  creating build\lib\carball\analysis\stats\tendencies
  copying carball\analysis\stats\tendencies\averages.py -> build\lib\carball\analysis\stats\tendencies
  copying carball\analysis\stats\tendencies\hit_counts.py -> build\lib\carball\analysis\stats\tendencies       
  copying carball\analysis\stats\tendencies\positional_tendencies.py -> build\lib\carball\analysis\stats\tendencies
  copying carball\analysis\stats\tendencies\relative_position_tendencies.py -> build\lib\carball\analysis\stats\tendencies
  copying carball\analysis\stats\tendencies\speed_tendencies.py -> build\lib\carball\analysis\stats\tendencies 
  copying carball\analysis\stats\tendencies\team_tendencies.py -> build\lib\carball\analysis\stats\tendencies  
  copying carball\analysis\stats\tendencies\__init__.py -> build\lib\carball\analysis\stats\tendencies
  creating build\lib\carball\analysis\stats\utils
  copying carball\analysis\stats\utils\pandas_utils.py -> build\lib\carball\analysis\stats\utils
  copying carball\analysis\stats\utils\__init__.py -> build\lib\carball\analysis\stats\utils
  creating build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\ball.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\base.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\boost.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\camera.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\car.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\dropshot.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\game_event.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\game_info.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\jump.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\player.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\rumble.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\team.py -> build\lib\carball\json_parser\actor
  copying carball\json_parser\actor\__init__.py -> build\lib\carball\json_parser\actor
  creating build\lib\carball\json_parser\sanity_check
  copying carball\json_parser\sanity_check\sanity_check.py -> build\lib\carball\json_parser\sanity_check       
  copying carball\json_parser\sanity_check\__init__.py -> build\lib\carball\json_parser\sanity_check
  creating build\lib\carball\json_parser\sanity_check\base_checks
  copying carball\json_parser\sanity_check\base_checks\base_check.py -> build\lib\carball\json_parser\sanity_check\base_checks
  copying carball\json_parser\sanity_check\base_checks\game_check.py -> build\lib\carball\json_parser\sanity_check\base_checks
  copying carball\json_parser\sanity_check\base_checks\player_check.py -> build\lib\carball\json_parser\sanity_check\base_checks
  copying carball\json_parser\sanity_check\base_checks\__init__.py -> build\lib\carball\json_parser\sanity_check\base_checks
  creating build\lib\carball\json_parser\sanity_check\checks
  copying carball\json_parser\sanity_check\checks\ball_data_frame_check.py -> build\lib\carball\json_parser\sanity_check\checks
  copying carball\json_parser\sanity_check\checks\player_attributes_check.py -> build\lib\carball\json_parser\sanity_check\checks
  copying carball\json_parser\sanity_check\checks\player_data_frame_check.py -> build\lib\carball\json_parser\sanity_check\checks
  copying carball\json_parser\sanity_check\checks\__init__.py -> build\lib\carball\json_parser\sanity_check\checks
  creating build\lib\carball\json_parser\sanity_check\errors
  copying carball\json_parser\sanity_check\errors\errors.py -> build\lib\carball\json_parser\sanity_check\errors
  copying carball\json_parser\sanity_check\errors\__init__.py -> build\lib\carball\json_parser\sanity_check\errors
  creating build\lib\carball\tests\metadata
  copying carball\tests\metadata\command_line_test.py -> build\lib\carball\tests\metadata
  copying carball\tests\metadata\error_test.py -> build\lib\carball\tests\metadata
  copying carball\tests\metadata\leader_test.py -> build\lib\carball\tests\metadata
  copying carball\tests\metadata\offline_test.py -> build\lib\carball\tests\metadata
  copying carball\tests\metadata\__init__.py -> build\lib\carball\tests\metadata
  creating build\lib\carball\tests\stats
  copying carball\tests\stats\boost_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\demo_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\dribble_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\dropshot_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\fifty_fifty_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\hit_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\kickoff_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\rumble_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\team_test.py -> build\lib\carball\tests\stats
  copying carball\tests\stats\__init__.py -> build\lib\carball\tests\stats
  running egg_info
  writing carball.egg-info\PKG-INFO
  writing dependency_links to carball.egg-info\dependency_links.txt
  writing entry points to carball.egg-info\entry_points.txt
  writing requirements to carball.egg-info\requires.txt
  writing top-level names to carball.egg-info\top_level.txt
  reading manifest file 'carball.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'carball\generated\*'
  warning: no previously-included files found matching 'carball\rattletrap\rattletrap-*'
  writing manifest file 'carball.egg-info\SOURCES.txt'
  creating build\lib\carball\generated
  creating build\lib\carball\generated\api
  copying carball\generated\api\__init__.py -> build\lib\carball\generated\api
  copying carball\generated\api\game_pb2.py -> build\lib\carball\generated\api
  copying carball\generated\api\party_pb2.py -> build\lib\carball\generated\api
  copying carball\generated\api\player_id_pb2.py -> build\lib\carball\generated\api
  copying carball\generated\api\player_pb2.py -> build\lib\carball\generated\api
  copying carball\generated\api\team_pb2.py -> build\lib\carball\generated\api
  creating build\lib\carball\generated\api\metadata
  copying carball\generated\api\metadata\__init__.py -> build\lib\carball\generated\api\metadata
  copying carball\generated\api\metadata\camera_settings_pb2.py -> build\lib\carball\generated\api\metadata    
  copying carball\generated\api\metadata\game_metadata_pb2.py -> build\lib\carball\generated\api\metadata      
  copying carball\generated\api\metadata\mutators_pb2.py -> build\lib\carball\generated\api\metadata
  copying carball\generated\api\metadata\player_loadout_pb2.py -> build\lib\carball\generated\api\metadata     
  creating build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\__init__.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\ball_stats_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\data_frame_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\dropshot_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\events_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\extra_mode_stats_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\game_stats_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\goal_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\kickoff_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\per_possession_stats_pb2.py -> build\lib\carball\generated\api\stats     
  copying carball\generated\api\stats\player_stats_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\rumble_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\stats_pb2.py -> build\lib\carball\generated\api\stats
  copying carball\generated\api\stats\team_stats_pb2.py -> build\lib\carball\generated\api\stats
  creating build\lib\carball\generated\binaries
  copying carball\generated\binaries\__init__.py -> build\lib\carball\generated\binaries
  copying carball\analysis\PROTOBUF_VERSION -> build\lib\carball\analysis
  copying carball\rattletrap\cloud_parser-9.0.3-linux -> build\lib\carball\rattletrap
  copying carball\analysis\events\hit_detection\hitbox\Vehicle Specifications v1.39 - Hitboxes, Handling.xlsx -> build\lib\carball\analysis\events\hit_detection\hitbox
  installing to build\bdist.win-amd64\wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\MyUser\AppData\Local\Temp\pip-install-ak5nbgls\carball\setup.py", line 65, in <module>       
      'console_scripts': ['carball=carball.command_line:main']
    File "c:\python\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "distutils\core.py", line 148, in setup
    File "distutils\dist.py", line 955, in run_commands
    File "distutils\dist.py", line 974, in run_command
    File "c:\python\lib\site-packages\wheel\bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "distutils\cmd.py", line 313, in run_command
    File "distutils\dist.py", line 974, in run_command
    File "C:\Users\MyUser\AppData\Local\Temp\pip-install-ak5nbgls\carball\setup.py", line 39, in run
      from init import initialize_project
  ModuleNotFoundError: No module named 'init'
  ----------------------------------------
  ERROR: Failed building wheel for carball
  Running setup.py clean for carball
Failed to build carball
Installing collected packages: carball
    Running setup.py install for carball ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MyUser\\AppData\\Local\\Temp\\pip-install-ak5nbgls\\carball\\setup.py'"'"'; __file__='"'"'C:\\Users\\MyUser\\AppData\\Local\\Temp\\pip-install-ak5nbgls\\carball\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MyUser\AppData\Local\Temp\pip-record-cesgf_8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\Include\carball'
         cwd: C:\Users\MyUser\AppData\Local\Temp\pip-install-ak5nbgls\carball\
    Complete output (13 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MyUser\AppData\Local\Temp\pip-install-ak5nbgls\carball\setup.py", line 65, in <module>     
        'console_scripts': ['carball=carball.command_line:main']
line 144, in setup
        return distutils.core.setup(**attrs)
      File "distutils\core.py", line 148, in setup
      File "distutils\dist.py", line 955, in run_commands
      File "distutils\dist.py", line 974, in run_command
      File "C:\Users\MyUser\AppData\Local\Temp\pip-install-ak5nbgls\carball\setup.py", line 39, in run
        from init import initialize_project
    ModuleNotFoundError: No module named 'init'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MyUser\\AppData\\Local\\Temp\\pip-install-ak5nbgls\\carball\\setup.py'"'"'; __file__='"'"'C:\\Users\\MyUser\\AppData\\Local\\Temp\\pip-install-ak5nbgls\\carball\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MyUser\AppData\Local\Temp\pip-record-cesgf_8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\Include\carball' Check the logs for full command output.
```

**Comment by Sciguymjm** [comment]
Until we can get a fix in, use `python -m easy_install carball`

**Comment by Gurey** [comment]
I solved this by manually adding carball to my embed python by copy carball from my global python installation.

Thanks for the attention though!
