### ISSUE TITLE
carball 0.3.0 breaks on the replay host joining late (presumably)

### ISSUE THREAD

**Issue by Sciguymjm** [SaltieRL/carball#38]
https://cdn.discordapp.com/attachments/412423088521740288/490247165046685696/1E9B0E044A80E084534F6381517D5D82.replay

```
carball.analyze_replay_file('replays/1E9B0E044A80E084534F6381517D5D82.replay', 'replays/1E9B0E044A80E084534F6381517D5D82.replay.json')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/matthew/PycharmProjects/ReplayAnalysis/3.6/lib/python3.6/site-packages/carball/decompile_replays.py", line 68, in analyze_replay_file
    game = Game(loaded_json=_json)
  File "/home/matthew/PycharmProjects/ReplayAnalysis/3.6/lib/python3.6/site-packages/carball/json_parser/game.py", line 64, in __init__
    self.all_data = self.parse_replay()
  File "/home/matthew/PycharmProjects/ReplayAnalysis/3.6/lib/python3.6/site-packages/carball/json_parser/game.py", line 341, in parse_replay
    player_ball_data[player_actor_id][frame_number] = data_dict
KeyError: 5
```

**Comment by hallo-doei** [comment]
When watching the replay in RL itself it seems like the game does not have people leaving nor people joining, I did however join one second late, so after the first kickoff already started.

**Comment by Destiphy** [comment]
That replay provided also produces the bug described in https://github.com/SaltieRL/carball/issues/24 because of a playername in the game.

(It occurs afterwards)
